// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SplitWiseDatabase.Models;

namespace SplitWiseDatabase.Migrations
{
    [DbContext(typeof(Splitwise))]
    partial class SplitwiseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SplitWiseDatabase.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName");

                    b.HasKey("ActivityId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Balance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BalanceAmount");

                    b.HasKey("BalanceId");

                    b.ToTable("balances");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillAmount");

                    b.Property<int?>("BillCatagoryId");

                    b.Property<DateTime>("BillDate");

                    b.Property<string>("BillImage");

                    b.Property<string>("BillName");

                    b.Property<string>("BillNote");

                    b.Property<string>("BillReminder");

                    b.Property<string>("BillRepeats");

                    b.Property<string>("Catagory");

                    b.Property<int?>("CatagoryOptionId");

                    b.Property<int?>("PaymentId");

                    b.Property<int?>("ReminderId");

                    b.Property<int?>("RepeatsId");

                    b.Property<string>("catagoryOption");

                    b.HasKey("BillId");

                    b.HasIndex("BillCatagoryId");

                    b.HasIndex("CatagoryOptionId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReminderId");

                    b.HasIndex("RepeatsId");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.BillCatagory", b =>
                {
                    b.Property<int>("BillCatagoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatagoryName");

                    b.HasKey("BillCatagoryId");

                    b.ToTable("BillCatagories");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.CatagoryOption", b =>
                {
                    b.Property<int>("CatagoryOptionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatagoryOptionName");

                    b.HasKey("CatagoryOptionId");

                    b.ToTable("catagoryOptions");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Friends", b =>
                {
                    b.Property<int>("FriendsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityId");

                    b.Property<string>("FriendEmail");

                    b.Property<string>("FriendName");

                    b.Property<int?>("GroupId");

                    b.Property<int?>("OwesId");

                    b.Property<int?>("PaymentId");

                    b.Property<int?>("SattleupId");

                    b.Property<int?>("SharedId");

                    b.HasKey("FriendsId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwesId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SattleupId");

                    b.HasIndex("SharedId");

                    b.ToTable("friends");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BalanceId");

                    b.Property<int?>("BillId");

                    b.Property<string>("GroupName");

                    b.Property<int?>("OwesId");

                    b.Property<int?>("SattleupId");

                    b.Property<int?>("SharedId");

                    b.HasKey("GroupId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("BillId");

                    b.HasIndex("OwesId");

                    b.HasIndex("SattleupId");

                    b.HasIndex("SharedId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Owes", b =>
                {
                    b.Property<int>("OwesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OwesAmmount");

                    b.HasKey("OwesId");

                    b.ToTable("owes");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PayMode");

                    b.Property<int?>("PaymentModeId");

                    b.Property<int>("PaymentReceive");

                    b.Property<int>("Paymentmade");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PayMode");

                    b.HasKey("PaymentModeId");

                    b.ToTable("paymentModes");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReminderName");

                    b.HasKey("ReminderId");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Repeats", b =>
                {
                    b.Property<int>("RepeatsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RepeatsName");

                    b.HasKey("RepeatsId");

                    b.ToTable("repeats");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.SattleUp", b =>
                {
                    b.Property<int>("SattleupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SattleAmount");

                    b.HasKey("SattleupId");

                    b.ToTable("sattleUps");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Shared", b =>
                {
                    b.Property<int>("SharedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SharedAmmount");

                    b.HasKey("SharedId");

                    b.ToTable("shareds");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityId");

                    b.Property<int?>("BalanceId");

                    b.Property<int?>("BillId");

                    b.Property<string>("EmailId");

                    b.Property<int?>("FriendsId");

                    b.Property<int?>("GroupId");

                    b.Property<int?>("OwesId");

                    b.Property<int?>("PaymentId");

                    b.Property<int?>("SattleupId");

                    b.Property<int?>("SharedId");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("BillId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwesId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SattleupId");

                    b.HasIndex("SharedId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Bill", b =>
                {
                    b.HasOne("SplitWiseDatabase.Models.BillCatagory", "BillCatagory")
                        .WithMany()
                        .HasForeignKey("BillCatagoryId");

                    b.HasOne("SplitWiseDatabase.Models.CatagoryOption", "CatagoryOption")
                        .WithMany()
                        .HasForeignKey("CatagoryOptionId");

                    b.HasOne("SplitWiseDatabase.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("SplitWiseDatabase.Models.Reminder", "Reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId");

                    b.HasOne("SplitWiseDatabase.Models.Repeats", "Repeats")
                        .WithMany()
                        .HasForeignKey("RepeatsId");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Friends", b =>
                {
                    b.HasOne("SplitWiseDatabase.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("SplitWiseDatabase.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SplitWiseDatabase.Models.Owes", "Owes")
                        .WithMany()
                        .HasForeignKey("OwesId");

                    b.HasOne("SplitWiseDatabase.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("SplitWiseDatabase.Models.SattleUp", "SattleUp")
                        .WithMany()
                        .HasForeignKey("SattleupId");

                    b.HasOne("SplitWiseDatabase.Models.Shared", "Shared")
                        .WithMany()
                        .HasForeignKey("SharedId");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Group", b =>
                {
                    b.HasOne("SplitWiseDatabase.Models.Balance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId");

                    b.HasOne("SplitWiseDatabase.Models.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("SplitWiseDatabase.Models.Owes", "Owes")
                        .WithMany()
                        .HasForeignKey("OwesId");

                    b.HasOne("SplitWiseDatabase.Models.SattleUp", "SattleUp")
                        .WithMany()
                        .HasForeignKey("SattleupId");

                    b.HasOne("SplitWiseDatabase.Models.Shared", "Shared")
                        .WithMany()
                        .HasForeignKey("SharedId");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.Payment", b =>
                {
                    b.HasOne("SplitWiseDatabase.Models.PaymentMode", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId");
                });

            modelBuilder.Entity("SplitWiseDatabase.Models.User", b =>
                {
                    b.HasOne("SplitWiseDatabase.Models.Activity", "activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("SplitWiseDatabase.Models.Balance", "balance")
                        .WithMany()
                        .HasForeignKey("BalanceId");

                    b.HasOne("SplitWiseDatabase.Models.Bill", "bill")
                        .WithMany()
                        .HasForeignKey("BillId");

                    b.HasOne("SplitWiseDatabase.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId");

                    b.HasOne("SplitWiseDatabase.Models.Group", "group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SplitWiseDatabase.Models.Owes", "owes")
                        .WithMany()
                        .HasForeignKey("OwesId");

                    b.HasOne("SplitWiseDatabase.Models.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("SplitWiseDatabase.Models.SattleUp", "sattleUp")
                        .WithMany()
                        .HasForeignKey("SattleupId");

                    b.HasOne("SplitWiseDatabase.Models.Shared", "shared")
                        .WithMany()
                        .HasForeignKey("SharedId");
                });
#pragma warning restore 612, 618
        }
    }
}
