// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Splitwise.Models;

namespace Splitwise.Migrations
{
    [DbContext(typeof(SplitwiseContext))]
    partial class SplitwiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Splitwise.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityName");

                    b.Property<int>("FriendsId");

                    b.Property<int>("UserId");

                    b.HasKey("ActivityId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("UserId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("Splitwise.Models.Balance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BalanceAmount");

                    b.Property<int>("FriendsId");

                    b.Property<int>("UserId");

                    b.HasKey("BalanceId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("UserId");

                    b.ToTable("balances");
                });

            modelBuilder.Entity("Splitwise.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillAmount");

                    b.Property<int?>("BillCatagoryId");

                    b.Property<string>("BillCatagoryName");

                    b.Property<DateTime>("BillDate");

                    b.Property<string>("BillImage");

                    b.Property<string>("BillName");

                    b.Property<string>("BillNote");

                    b.Property<string>("BillReminder");

                    b.Property<string>("BillRepeats");

                    b.Property<string>("Catagory");

                    b.Property<int?>("CatagoryOptionId");

                    b.Property<string>("CatagoryOptionName");

                    b.Property<int?>("ReminderId");

                    b.Property<int>("ReminderName");

                    b.Property<int?>("RepeatsId");

                    b.Property<int>("RepeatsName");

                    b.Property<int>("UserId");

                    b.HasKey("BillId");

                    b.HasIndex("BillCatagoryId");

                    b.HasIndex("CatagoryOptionId");

                    b.HasIndex("ReminderId");

                    b.HasIndex("RepeatsId");

                    b.HasIndex("UserId");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("Splitwise.Models.BillCatagory", b =>
                {
                    b.Property<int>("BillCatagoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillCatagoryName");

                    b.HasKey("BillCatagoryId");

                    b.ToTable("BillCatagories");
                });

            modelBuilder.Entity("Splitwise.Models.CatagoryOption", b =>
                {
                    b.Property<int>("CatagoryOptionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatagoryOptionName");

                    b.HasKey("CatagoryOptionId");

                    b.ToTable("catagoryOptions");
                });

            modelBuilder.Entity("Splitwise.Models.Friends", b =>
                {
                    b.Property<int>("FriendsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FriendEmail");

                    b.Property<string>("FriendName");

                    b.HasKey("FriendsId");

                    b.ToTable("friends");
                });

            modelBuilder.Entity("Splitwise.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendsId");

                    b.Property<string>("GroupName");

                    b.Property<int>("UserId");

                    b.HasKey("GroupId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("UserId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Splitwise.Models.Owes", b =>
                {
                    b.Property<int>("OwesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendsId");

                    b.Property<int>("OwesAmmount");

                    b.HasKey("OwesId");

                    b.HasIndex("FriendsId");

                    b.ToTable("owes");
                });

            modelBuilder.Entity("Splitwise.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendsId");

                    b.Property<int>("PaymentReceive");

                    b.Property<int>("Paymentmade");

                    b.Property<int>("UserId");

                    b.HasKey("PaymentId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("UserId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Splitwise.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PayMode");

                    b.HasKey("PaymentModeId");

                    b.ToTable("paymentModes");
                });

            modelBuilder.Entity("Splitwise.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReminderName");

                    b.HasKey("ReminderId");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("Splitwise.Models.Repeats", b =>
                {
                    b.Property<int>("RepeatsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RepeatsName");

                    b.HasKey("RepeatsId");

                    b.ToTable("repeats");
                });

            modelBuilder.Entity("Splitwise.Models.SattleUp", b =>
                {
                    b.Property<int>("SattleUpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendsId");

                    b.Property<int>("PaymentModeId");

                    b.Property<int>("SattleAmount");

                    b.Property<int>("UserId");

                    b.HasKey("SattleUpId");

                    b.HasIndex("FriendsId");

                    b.HasIndex("PaymentModeId");

                    b.HasIndex("UserId");

                    b.ToTable("sattleUps");
                });

            modelBuilder.Entity("Splitwise.Models.Shared", b =>
                {
                    b.Property<int>("SharedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SharedAmmount");

                    b.Property<int>("UserId");

                    b.HasKey("SharedId");

                    b.HasIndex("UserId");

                    b.ToTable("shareds");
                });

            modelBuilder.Entity("Splitwise.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailId");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Splitwise.Models.Activity", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Balance", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Bill", b =>
                {
                    b.HasOne("Splitwise.Models.BillCatagory", "billCatagory")
                        .WithMany()
                        .HasForeignKey("BillCatagoryId");

                    b.HasOne("Splitwise.Models.CatagoryOption", "catagoryOption")
                        .WithMany()
                        .HasForeignKey("CatagoryOptionId");

                    b.HasOne("Splitwise.Models.Reminder", "reminder")
                        .WithMany()
                        .HasForeignKey("ReminderId");

                    b.HasOne("Splitwise.Models.Repeats", "repeats")
                        .WithMany()
                        .HasForeignKey("RepeatsId");

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Group", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Owes", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Payment", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.SattleUp", b =>
                {
                    b.HasOne("Splitwise.Models.Friends", "friends")
                        .WithMany()
                        .HasForeignKey("FriendsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.PaymentMode", "paymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Splitwise.Models.Shared", b =>
                {
                    b.HasOne("Splitwise.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
